# Dependencies
highlighter:      rouge

# Permalinks
permalink:        pretty
#relative_permalinks: true

gems: [jekyll-paginate,jekyll-gist]

# Setup
title:            Chen Lu
tagline:          'Game Programmer Portfolio'
description:      'Game Programmer Portfolio Site'
url:              http://paspy.me/
baseurl:          /

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/paspy/
